/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VBadge: typeof import('primevue/badge')['default']
    VButton: typeof import('primevue/button')['default']
    VForm: typeof import('@primevue/forms/form')['default']
    VFormField: typeof import('@primevue/forms/formfield')['default']
    VIconField: typeof import('primevue/iconfield')['default']
    VInputIcon: typeof import('primevue/inputicon')['default']
    VInputNumber: typeof import('primevue/inputnumber')['default']
    VInputText: typeof import('primevue/inputtext')['default']
    VMenu: typeof import('primevue/menu')['default']
    VMessage: typeof import('primevue/message')['default']
    VSelect: typeof import('primevue/select')['default']
    VSlider: typeof import('primevue/slider')['default']
    VTab: typeof import('primevue/tab')['default']
    VTabList: typeof import('primevue/tablist')['default']
    VTabPanel: typeof import('primevue/tabpanel')['default']
    VTabPanels: typeof import('primevue/tabpanels')['default']
    VTabs: typeof import('primevue/tabs')['default']
    VTree: typeof import('primevue/tree')['default']
  }
}
