/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VButton: typeof import('primevue/button')['default']
    VForm: typeof import('@primevue/forms/form')['default']
    VFormField: typeof import('@primevue/forms/formfield')['default']
    VInputText: typeof import('primevue/inputtext')['default']
    VMessage: typeof import('primevue/message')['default']
    VToast: typeof import('primevue/toast')['default']
  }
}
